version: "3.9"

services:
  database: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: database_petshop
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker_petshop
      - POSTGRES_PASSWORD=password_petshop
      - POSTGRES_DB=petshop
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: app_petshop
    restart: always
    ports: 
      - 3000:3000
    volumes: 
      - .:/usr/app
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
